### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by brisberg** [screepers/screeps-server-mockup#26]
Should we do a new release to fix compatibility with screeps 4.1.5?

#23

**Comment by pyrodogg** [comment]
Forgot to follow up on that after the PR. I'll see if I can get one pushed this evening.

**Comment by pyrodogg** [comment]
1.5.1 release posted to [Github](https://github.com/screepers/screeps-server-mockup/releases/tag/v1.5.1) and [NPM](https://www.npmjs.com/package/screeps-server-mockup).

Reopen if there are any issues.

**Comment by brisberg** [comment]
Thanks, cheers!
