### ISSUE TITLE
lodash rename issue during install

### ISSUE THREAD

**Issue by legion0** [screepers/screeps-server-mockup#27]
Getting error trying to install, running:
npm i -D screeps-server-mockup

complaining about failing to rename /home/legion/workspace/screeps/node_modules/@screeps/backend/node_modules/lodash

why is there a node_modules inside node_modules ? seems odd to me (node noob here).

[2020-04-24T21_03_32_483Z-debug.log](https://github.com/screepers/screeps-server-mockup/files/4531564/2020-04-24T21_03_32_483Z-debug.log)
[terminal-output.txt](https://github.com/screepers/screeps-server-mockup/files/4531565/terminal-output.txt)

**Comment by Hiryus** [comment]
Having several `node_modules` is a normal behavior: each module may have its own dependencies inside its own `node_modules` (this is a big complaint about npm by the may).

I never got this error though.
* Can you make sure the permission on the node_modules folder are correct ?
* Are you using Windows Subsystem for linux ?
* Your version is not old, but just in case, try updating to the last npm version (process depends on how you installed it, but `npm install npm@latest -g` usually works).

**Comment by legion0** [comment]
yes I am using WSL, i check permissions and they all seem fine user+group correct and drwxrwxrwx on all directories.
updated npm as suggested but still getting the same error

**Comment by legion0** [comment]
did a hard reset of all packages and that fixed the issue

rm -rf node_modules package-lock.json && npm install
npm i -D screeps-server-mockup
