### ISSUE TITLE
Typescript conversion

### ISSUE THREAD

**Issue by brisberg** [screepers/screeps-server-mockup#7]
How does the team feel about converting this library to Typescript?

The advantage is that compiling from Typescript will automatically produce a .d.ts typings file, which downstream projects can use for type completions. Since this project is referenced from the `screeps-typescript-starter`, it would make sense to provide some good typings for it.

The typings can be kept in sync with @types/screeps as we update the Screeps version in the future.

If distributed in compiled form on NPM, this library will still be consumable from Javascript without typings just as it is now:

```
// test.js
const {ScreepsServer} = require('screeps-server-mockup');
```

```
// test.ts
import {ScreepsServer} from 'screeps-server-mockup';
```

---

I am willing to put up a PR for the conversion, if you guys think it would be desirable for longterm maintainability.

**Comment by pyrodogg** [comment]
Yes, i'm all in for Typescript, a PR would be appreciated. If needed, we can merge it into a `ts-port` branch it it needs more time to simmer, allow others to contribute as well.

**Comment by brisberg** [comment]
Great. I'll do a pass this weekend or next week and see if I hit any snags. I'll put up a PR with my results.

**Comment by brisberg** [comment]
This conversion is nearly done once #11 #12 #13 #14 are merged into the `typescript` branch.

**Comment by pyrodogg** [comment]
Thanks. I had a few minutes this morning and got most of them merged, only #14 is left.

**Comment by brisberg** [comment]
Thanks! Yeah I wasn’t sure if they would all merge cleanly, but I’ll sync and update the last one this week.

I think put up a few more later to finalize the publish process. And I was working on a branch on my own AI which successfully consumed the TS version of this library! I’ll adapt it into an example branch soon.

**Comment by brisberg** [comment]
Couple more, and then I believe the `typescript` branch is ready for user testing: #14 #17 #18 #19

**Comment by brisberg** [comment]
I believe that this should be ready for a full release. I'm was using it for my project, but I haven't prepared those to present as a simple example. Let me know if there is anything else you'd like to add
